apiVersion: apps/v1
kind: Deployment
metadata:
  name: bashbrew
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bashbrew
    spec:
      containers:
      - image: wpass.azurecr.io/bashbrew:latest
        name: bashbrew
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      
---
apiVersion: apps/v1
kind: Service
metadata:
  name: bashbrew
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: bashbrew
  type: LoadBalancer
