apiVersion: v1
kind: Namespace
metadata:
  name: wpaas-prod

---
# K8 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpass-site
  namespace: wpaas-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wpass-site
        ### Add New Image Here...
        image: 657555487464.dkr.ecr.us-west-2.amazonaws.com/wpass-dev:caweb-multisite-v9
        env:
        - name:  WORDPRESS_WEBSITE_URL_WITHOUT_HTTP 
          value: cawebdemo.wpaas.org
        - name: WORDPRESS_WEBSITE_TITLE
          value: "demosite"
        - name: WORDPRESS_ADMIN_USER
          value: "demouser"
        - name: WORDPRESS_ADMIN_PASSWORD
          value: "test123"
        - name: WORDPRESS_ADMIN_EMAIL
          value: "sreekar.peddi@state.ca.gov"
        - name: WEB_ROOT
          value: "/usr/src/wordpress/"
        - name: WORDPRESS_DB_NAME
          value: "cawebdb2020"
        - name: WORDPRESS_DB_USER
          value: "wpadmin"
        - name: WORDPRESS_DB_PASSWORD
          value: "wpadmin1234"
        - name: WORDPRESS_DB_HOST
          value: "wpaasdb.cydwunev2mr4.us-west-2.rds.amazonaws.com"
        - name: WORDPRESS_WEBSITE_POST_URL_STRUCTURE
          value: "/blog/%postname%/"
        - name: WP_DEFAULT_THEME
          value: "CAWeb"
        
        ports:
            - containerPort: 80
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/wp-content        
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: wp-data
       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wpass-site
  namespace: wpaas-prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress

---
#Horizontal pod autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wpass-site
  namespace: wpaas-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wpass-site
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: 'true'

---
# Persistance Volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-data
  namespace: wpaas-prod
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  #storageClassName: standard
